extends: default

rules:
  line-length: disable
  document-start: disable
  new-line-at-end-of-file: disable
  trailing-spaces: disable
  braces: disable
  brackets: disable
  indentation:
    spaces: 2
    indent-sequences: consistent